"""your message

Revision ID: 873a749f58e8
Revises: 4e14c24dd524
Create Date: 2024-09-22 18:40:52.544721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873a749f58e8'
down_revision = '4e14c24dd524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
